name: simplehttpconnection
description: Simple Httpconnection
version: 1.0.1
author: Mochamad Nizwar Syafuan <nizwar@merahputih.id>
homepage: https://github.com/nizwar/simplehttpconnection

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter  