name: simplehttpconnection
description: Best simple way to request data with Simplehttpconnection - by Nizwar
version: 1.2.1
author: Mochamad Nizwar Syafuan <nizwar@merahputih.id>
homepage: https://github.com/nizwar/simplehttpconnection

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies: 
  http: ^0.12.0+2
  path: ^1.6.4
  path_provider: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter  